export type ICountrySelectLanguages =
  | 'ara' // Arabic
  | 'bel' // Belarusian
  | 'bre' // Breton
  | 'bul' // Bulgarian
  | 'ces' // Czech
  | 'deu' // German
  | 'ell' // Greek
  | 'eng' // English
  | 'est' // Estonian
  | 'fin' // Finnish
  | 'fra' // French
  | 'heb' // Hebrew
  | 'hrv' // Croatian
  | 'hun' // Hungarian
  | 'ita' // Italian
  | 'jpn' // Japanese
  | 'kor' // Korean
  | 'nld' // Dutch
  | 'per' // Persian
  | 'pol' // Polish
  | 'por' // Portuguese
  | 'ron' // Romanian
  | 'rus' // Russian
  | 'slk' // Slovak
  | 'spa' // Spanish
  | 'srp' // Serbian
  | 'swe' // Swedish
  | 'tur' // Turkish
  | 'ukr' // Ukrainian
  | 'urd' // Urdu
  | 'zho' // Chinese
  | 'zho-Hans' // Simplified Chinese
  | 'zho-Hant'; // Traditional Chinese
